# Generated by Django 4.2.30 on 2026-08-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_total_amount_alter_booking_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='showseat',
            constraint=models.UniqueConstraint(fields=('show', 'seat'), name='unique_show_seat'),
        ),
    ]
