# Generated by Django 4.2.30 on 2026-08-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_payment_booking_dashboard_b_booked__5e5ee1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='dashboard_b_booked__5e5ee1_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='dashboard_b_movie_i_2a8d41_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='dashboard_b_theater_4ef831_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='dashboard_b_user_id_3f7847_idx',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
