# Generated by Django 4.2.30 on 2026-08-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_payment_booking_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at', 'status'], name='dashboard_b_booked__5e5ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'booked_at'], name='dashboard_b_status_4ae703_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie', 'status'], name='dashboard_b_movie_i_2a8d41_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'status'], name='dashboard_b_theater_4ef831_idx'),
        ),
    ]
