# Generated by Django 4.2.30 on 2026-09-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_booking_dashboard_b_booked__5e5ee1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='dashboard_b_booked__5e5ee1_idx',
        ),
    ]
