# Generated by Django 4.2.30 on 2026-09-13 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100, unique=True)),
                ('movie_name', models.CharField(max_length=200)),
                ('theater', models.CharField(max_length=200)),
                ('screen', models.CharField(max_length=100)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('seats', models.CharField(max_length=200)),
                ('payment_reference', models.CharField(max_length=200)),
                ('payment_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('ticket_pdf', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='tickets/qr/')),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
